apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-auth-deployment
    lables:
        app: users-auth-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: users-auth
    template:
        metadata:
            labels:
                app: users-auth
        spec:
            containers:
                - name: users-auth-container
                  image: jihnordraven/users-auth:latest
